### ISSUE TITLE
GPTInformal TTS dataset

### ISSUE THREAD

**Issue by MahtaFetrat** [karim23657/awesome-Persian-Speech#5]
Hello @karim23657,
Thank you for sharing the freely licensed Mana-TTS dataset! I hope it will encourage more open-source contributions in the field. I’d like to introduce another CC0-licensed TTS dataset called [GPTInformal](https://github.com/MahtaFetrat/GPTInformal-Persian-Speech-Dataset). It currently contains over 6 hours of paired audio and text chunks, with room for future expansion. The text was generated by prompting GPT-4 on various topics, and the audio was recorded in a controlled, silent environment.

Best wishes,
Mahta Fetrat

**Comment by karim23657** [comment]
@MahtaFetrat , Thank you.
Repo updated.
